### ISSUE TITLE
Appending the date in the initramfs & kernel name

### ISSUE THREAD

**Issue by GuillaumeSeren** [Sabayon/genkernel-next#34]
Hello,
I try to follow the kernel tree, and add some patches on my own, so I need to add the date in my kernel name to keep track, and also to have an unique name.

Since I migrated to gentoo, I did that using the '--kernname' param, but in my new setup UEFI / LUKS /BTRFS, I noticed that 'grub2-mkconfig' did not find the initrd (but find the kernel).
It was due to the /etc/grub.d/10_linux
```
  initrd=
  for i in "initrd.img-${version}" "initrd-${version}.img" "initrd-${version}.gz" \
	   "initrd-${version}" "initramfs-${version}.img" \
	   "initrd.img-${alt_version}" "initrd-${alt_version}.img" \
	   "initrd-${alt_version}" "initramfs-${alt_version}.img" \
	   "initramfs-genkernel-${version}" \
	   "initramfs-genkernel-${alt_version}" \
	   "initramfs-genkernel-${GENKERNEL_ARCH}-${version}" \
	   "initramfs-genkernel-${GENKERNEL_ARCH}-${alt_version}"; do
    if test -e "${dirname}/${i}" ; then
      initrd="$i"
      break
    fi
  done
```
So I started tweaking again with the 'kernname' param but this param only change the middle part of the name (ie 'genkernel') and so if I put a date here it break the detection of grub2-mkconfig, and I don't think it is the right place to put that, so it seem's more logical to add a new param to append at the end of the name the date or anything you want to get an unique name.

The standard genkernel naming
```
kernel-genkernel-x86_64-4.4.6-gentoo
```
Tweaking with kernname
```
kernel-genkernel-2016-06-11_2052-x86_64-4.7.0-rc2-git
```
The naming with the date at the end
```
kernel-genkernel-x86_64-4.4.6-gentoo-2016-06-11_1945
```

If I am missing a better way of doing that please let me know.

**Comment by GuillaumeSeren** [comment]
I just added the param in my fork of genkernel so it can be tested out in the branch add-appendname-param (07ca907).

**Comment by dorvan** [comment]
i suggest to fix the date as 20160613-232800 YYYYMMDD-HHMMSS as standard like volume snapshots.

**Comment by GuillaumeSeren** [comment]
@dorvan I try to follow the date format ISO 8601, but I upgraded the default date as you suggested in 'genkernel.conf', and as you can put anything in it, it will be easy to change it. (824b8fb)

**Comment by mudler** [comment]
Thanks, merged, i'll spin some rounds of tests before cutting a new rel. Feel free to re-open if needed.

**Comment by GuillaumeSeren** [comment]
Great ! :+1:

**Comment by dorvan** [comment]
Thanks!!!!!
