### ISSUE TITLE
arm arch has no kernel_config

### ISSUE THREAD

**Issue by daviessm** [Sabayon/genkernel-next#38]
When running genkernel for the first time using on an arm device, this error is output:
- Gentoo Linux Genkernel; Version 64
- Running with options: --btrfs all
- Using genkernel.conf from /etc/genkernel.conf
- Sourcing arch-specific config.sh from /usr/share/genkernel/arch/arm/config.sh ..
- Sourcing arch-specific modules_load from /usr/share/genkernel/arch/arm/modules_load ..
- ERROR: Error: No kernel .config specified, or file not found!
- 
- -- Grepping log... --
- 
- Running with options: --btrfs all
- Using genkernel.conf from /etc/genkernel.conf
- Sourcing arch-specific config.sh from /usr/share/genkernel/arch/arm/config.sh ..
- Sourcing arch-specific modules_load from /usr/share/genkernel/arch/arm/modules_load ..
  *
- ERROR: Error: No kernel .config specified, or file not found!
- 
- -- End log... --
- 
- Please consult /var/log/genkernel.log for more information and any
- errors that were reported above.
- 
- Report any genkernel bugs to bugs.gentoo.org and
- assign your bug to genkernel@gentoo.org. Please include
- as much information as you can in your bug report; attaching
- /var/log/genkernel.log so that your issue can be dealt with effectively.
- 
- Please do _not_ report compilation failures as genkernel bugs!
- 

It appears there's no kernel_config file for arm. At least a message indicating how to proceed would be haelpful.

**Comment by sachsedd** [comment]
Solution:
copy config of current running kernel to /etc/kernels
e.g.:
zcat /proc/config.gz >/etc/kernels/kernel-config-5.10.61-gentoo-bpi-r2

**Comment by daviessm** [comment]
I don't use ARM any more so I'm going to close this issue.
