### ISSUE TITLE
LVM warnings during boot (lvmetad issue).

### ISSUE THREAD

**Issue by viewizard** [Sabayon/genkernel-next#42]
I use lvm (Gentoo sys-fs/lvm2-2.02.116-r6) and genkernel-next ver64 with LVM support. During boot all time I see warnings:

> File descriptor 3 (pipe:[1809]) leaked on lvm invocation. Parent PID 2330: /bin/sh
>   /run/lvm/lvmetad.socket: connect failed: No such file or directory 
>   WARNING: Failed to connect to lvmetad. Falling back to internal scanning.

The point of issue is:
1) lvm2 installed with /etc/lvm/lvm.conf configured use_lvmetad=1 by default, and forced to use lvmetad as dependence service. In the same time, genkernel-next copy this /etc/lvm/lvm.conf file without changes;
2) genkernel-next don't support lvmetad (don't even copy /sbin/lvmetad binary).

Frankly speaking, I am not even sure, are we need lvmetad during kernel boot at all, since we launch it later with system wide lvm.

I found reported bug in Gentoo with same issue during system boot, that was fixed:
https://bugs.gentoo.org/show_bug.cgi?id=577308

The idea is suppress error output "2>/dev/null" with lvmetad related warnings.
Second idea, since genkernel don't support /sbin/lvmetad, probably, we should provide in-line "--config use_lvmetad=0" configuration flag during lvm execution?

For now, I use changes for line https://github.com/Sabayon/genkernel-next/blob/master/defaults/initrd.d/00-fsdev.sh#L219
`printf "%b\n" "${cmds} --config use_lvmetad=0" | lvm /proc/self/fd/0 2>/dev/null || \`
and this work well for me (I use LUKS with LVM on it, including root).

**Comment by mudler** [comment]
Thanks for reporting :+1: 
this should be fixed now in new genkernel-next version
