### ISSUE TITLE
cryptsetup hangs because dmsetup is not included with LUKS="yes" and LVM="no"

### ISSUE THREAD

**Issue by sbraz** [Sabayon/genkernel-next#48]
Hi,
I have an encrypted root partition and no LVM but I had to select LVM="yes" in order to make my system bootable.
I think LUKS="yes" should cause genkernel to include /sbin/dmsetup in the initramfs as cryptsetup depends on it. After looking at gen_initramfs.sh, I didn't see any other missing binaries.

**Comment by mudler** [comment]
can you investigate if it's just dmsetup required or other components as well? cryptsetup requires lvm2 utilities.
otherwise seems reasonable to me for now to imply LVM="yes" when LUKS is requested.

**Comment by sbraz** [comment]
I'll try editing the .sh to just add dmsetup and I'll let you know tonight.

**Comment by sbraz** [comment]
Just adding dmsetup wasn't enough. It was still hanging. I guess it's reasonable to include LVM when LUKS is set. Maybe you want to add a comment explaining that in the conf file?

**Comment by mudler** [comment]
Thanks for confirming, don't think it's necessary, now it's done automatically when LUKS is enabled https://github.com/Sabayon/genkernel-next/commit/ccedb7524aabe256827538f5ca532319d520872e  but feel free to open a PR for the config changes. 

I'll close the issue now, re-open if necessary.
