### ISSUE TITLE
Please add BTRFS support

### ISSUE THREAD

**Issue by Massimo-B** [Sabayon/genkernel-next#51]
Hi,

I switched to gernkernel-next because of the plymouth support. Now I miss the option
```
BTRFS="yes"
```
in genkernel.conf comments.

Isn't this supported yet? Is genkernel-next development still more up-to-date than predecessor genkernel?

**Comment by mudler** [comment]
Hi,

btrfs is supported, but not listed in the default config file

**Comment by Massimo-B** [comment]
Thanks, then I will maybe migrate back to genkernel-next.
I need btrfs and GPG, which seems to be broken in genkernel without any comment:
https://github.com/robbat2/genkernel/issues/5
On genkernel-next I missed btrfs and went back. Is there a short summary what the difference in genkernel-next compared to genkernel actually is?
If btrfs is supported, adapt the default config file please.
