### ISSUE TITLE
sys-fs/mdadm udev rules are not appended to initramfs

### ISSUE THREAD

**Issue by buddyabaddon** [Sabayon/genkernel-next#56]
The udev rules from the sys-fs/mdadm package (63-md-raid-arrays.rules and 64-md-raid-assembly.rules) are not appended to the initramfs during creation. This causes mdadm raid arrays which depend on these udev rules to fail to assemble.
Features such as LVM have their udev rules explicitly appended to the initramfs. mdadm should have this same configuration behaviour.

My personal experience with this issue has been with imsm Intel fake raid0 container arrays.

Without the udev rules, the containers are created when the init script calls 'mdadm --assemble --scan' but the actual arrays within do not run and the user is dropped to an emergency shell upon boot. If the user then runs 'mdadm --run /dev/md[*]' for the container, the arrays can be forced to assemble.

If the mdadm udev rules are made part of the initramfs, the containers and arrays automatically assemble and run as expected without issue.

Others have reported this issue as well:
https://forums.gentoo.org/viewtopic-t-1025022-highlight-genkernel+imsm+mdadm.html
https://bugs.gentoo.org/496076#c17

I should have a fix via pull request shortly.

**Comment by mudler** [comment]
Guess we can close it now, thanks 👍
