### ISSUE TITLE
Add --compress-initramfs-type=lz4

### ISSUE THREAD

**Issue by fodrice** [Sabayon/genkernel-next#58]
Nothing to say here. Just add lz4 compression support.

**Comment by fodrice** [comment]
Okay, seeps it is allready done. There is no description in docs.
https://github.com/Sabayon/genkernel-next/blob/6175b913d090f88182b0b4b0b73fbf475c15a49e/doc/genkernel.8.txt#L391
need to be changed:
-Compression type for initramfs (best, xz, lzma, bzip2, gzip, lzop).
+Compression type for initramfs (best, xz, lzma, bzip2, gzip, lzop, lz4).

**Comment by buddyabaddon** [comment]
Here you go: https://github.com/Sabayon/genkernel-next/pull/59

**Comment by mudler** [comment]
I guess we can close it, thanks!
